### ISSUE TITLE
about train.h5 file you used in training

### ISSUE THREAD

**Issue by dongheehand** [sg-nm/Operation-wise-attention-network#12]
Thank you for your code and work!
I want to reproduce your results in the paper.

But train.h5 files are not exactly same because of the randomness when we generate the train.h5 file. I want to train the model using the train.h5 you used.

Can you upload or share the train.h5 file?

**Comment by sg-nm** [comment]
Thank you for the information.
I uploaded the train.h5 file, could you try it?
https://www.dropbox.com/s/4s01829s5ky3vx4/train.h5?dl=0

**Comment by dongheehand** [comment]
Thank you! I downloaded it.
Thank you very much!
