### ISSUE TITLE
About the size of the model?

### ISSUE THREAD

**Issue by ZuoYuShen** [sg-nm/Operation-wise-attention-network#2]
Hi,
Thanks to your amazing work!
I want to test your model in my own data, but it always out of memory, even if I try it on GTX 1080Ti. So I want to know the graphics card you use in your experiment.

**Comment by sg-nm** [comment]
Hi, thank you so much for testing our code.
For the dataset used in the RL-Restore paper, we used two GTX 1080Ti GPUs. Also, we used four GTX 1080Ti GPUs for our own dataset used in our paper.
