### ISSUE TITLE
About how to test my-own-dataset?

### ISSUE THREAD

**Issue by yff0815** [sg-nm/Operation-wise-attention-network#4]
hello ，good work,but I have a question.
I want to test your model in my own data, and i would like to know how toprepare my own dataset. My file structure is as follows;and i don't know what should i put in the target folder?
```
--Project
----dataset
------yourdata_test
--------input
----------1.jpg
----------2.jpg
 ...
--------target
```

**Comment by sg-nm** [comment]
Your structure described above is fine. Please make sure that the names of input images are the same as those of target images.

**Comment by yff0815** [comment]
Thanks so much for your reply! May I ask one more question?
In the current test code, you are still dealing with images with the size of 63x63, just the same as the training images. How do you deal with input image with other sizes? And do you resize the input image with the size of 63x63 first, then the output size determined the Output Layer?  Or you crop the original image into multi-patches with the size of 63x63, then put them into the network respectively, in the end, joint the output images together?
Thanks for your help in advance!

**Comment by sg-nm** [comment]
When we applied our model to input images with other sizes (e.g. object detection in our paper), we input the images into our network without cropping or resizing.

**Comment by yff0815** [comment]
Thanks so much!
