### ISSUE TITLE
What should I put in the ./dataset/val folder？

### ISSUE THREAD

**Issue by yff0815** [sg-nm/Operation-wise-attention-network#5]
I generate the training dataset using run RL-Restore，and then I put （train.h5）to `dataset/train/` , but when I run `python main.py -m mix -g 1`,  there is an error that `no such file named dataset /val/`
I would like to know what should I put in the `./dataset/val` folder？
hope for your helping, thank you so much!

**Comment by sg-nm** [comment]
The validation data (validation.h5) can be found at the [repository](https://github.com/yuke93/RL-Restore) of RL-Restore. Please put the validation.h5 to `./dataset/val/`.
