### ISSUE TITLE
about PSNR and SSIM

### ISSUE THREAD

**Issue by tang123456654321** [sg-nm/Operation-wise-attention-network#7]
Sorry to bother you, but I did have some problems running the code you provided.After I successfully run the code, the values of PSNR and SSIM are much higher than the data provided in your paper, which makes me feel a little confused, because I did not modify your code, except GPUID and batchsize.The train.h5 dataset is also generated from the file you mentioned, and validation. H5 is copied directly from rl-restore.I was wondering if there was a problem with validation data because you didn't mention the validate data in readme.md exactly.

**Comment by DongHwanJang** [comment]
@tang123456654321 How did you solve this issue?
