### ISSUE TITLE
about the value of PSNR and SSIM

### ISSUE THREAD

**Issue by tang123456654321** [sg-nm/Operation-wise-attention-network#9]
Sorry to bother you again.After I successfully run the trained model mode_best. pth, the result is PSNR=34.5027 and SSIM=0.7611, which is inconsistent with the value mentioned in the paper.

**Comment by sg-nm** [comment]
Can you let me know which dataset you used for evaluation, validation or test dataset?

**Comment by tang123456654321** [comment]
Thank you for your answer, but I've solved the problem.
